name: nightly-tests-desktop

concurrency:
  group: nightly-tests-desktop
  cancel-in-progress: true

on:
  schedule:
    # run every day at 4am UTC (11PM EST)
    - cron:  '0 4 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read    # This is required for actions/checkout

jobs:
  prod-sanity-browserstack:
    name: nightly-tests-desktop-browserstack
    runs-on: ubuntu-latest
    environment: production
    env:
      ACCTS_OIDC_EMAIL: ${{ secrets.E2E_ACCTS_OIDC_EMAIL }}
      ACCTS_OIDC_PWORD: ${{ secrets.E2E_ACCTS_OIDC_PWORD }}
      ACCTS_RECOVERY_EMAIL: ${{ secrets.E2E_ACCTS_RECOVERY_EMAIL }}
      PRIMARY_THUNDERMAIL_EMAIL: ${{ secrets.E2E_PRIMARY_THUNDERMAIL_EMAIL }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'test/e2e/package-lock.json'

      - name: Install dependencies
        run: |
          cd ./test/e2e
          npm install

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: 'Thunderbird Accounts'
          build-name: 'TB Accounts Nightly Tests (Desktop): BUILD_INFO'

      - name: Prod E2E Tests on Desktop Firefox
        # don't send GHA failure email if any of the E2E tests fail, can be annoying (I check the jobs each day in BrowserStack)
        continue-on-error: true
        run: |
          cd ./test/e2e
          cp .env.prod.example .env
          npm run prod-nightly-tests-browserstack-desktop-firefox

      - name: Prod E2E Tests on Desktop Chromium
        # don't send GHA failure email if any of the E2E tests fail, can be annoying (I check the jobs each day in BrowserStack)
        continue-on-error: true
        run: |
          cd ./test/e2e
          cp .env.prod.example .env
          npm run prod-nightly-tests-browserstack-desktop-chromium
